version: '3.8'

services:
  nginx:
    image: ghcr.io/pratikluitel/antipratik-nginx:dev
    ports:
      - "80:80"
    environment:
      - SERVER_NAME=${SERVER_NAME}
    depends_on:
      - api
      - ui
    networks:
      - antipratik-dev
    restart: unless-stopped

  api:
    image: ghcr.io/pratikluitel/antipratik-api:dev
    env_file: .env
    volumes:
      - /opt/antipratik-dev/config.yaml:/root/config.yaml
      - /opt/antipratik-dev/data:/data
    networks:
      - antipratik-dev
    restart: unless-stopped

  ui:
    image: ghcr.io/pratikluitel/antipratik-ui:dev
    networks:
      - antipratik-dev
    environment:
      - SERVER_API_URL=http://api:8080
    restart: unless-stopped

networks:
  antipratik-dev:
