FROM nginx:alpine
RUN apk add --no-cache gettext       # provides envsubst
COPY infrastructure/nginx.conf /etc/nginx/nginx.conf.template
# At startup: substitute ${SERVER_NAME} then launch nginx
CMD ["/bin/sh", "-c", "envsubst '${SERVER_NAME}' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"]