name: Build Check API

on:
  push:
    paths:
      - 'app/antipratik-api/**'

jobs:
  build-check-api:
    name: Build antipratik-api
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: app/antipratik-api/go.mod
          cache-dependency-path: app/antipratik-api/go.sum

      - name: Install libheif
        run: sudo apt-get install -y libheif-dev

      - name: Build
        working-directory: app/antipratik-api
        run: go build ./...
