name: Deploy

on:
  push:
    branches:
      - master
    paths:
      - 'sidequests/**'

jobs:
  deploy:
    name: Deploy sidequests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Publish sidequests to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: antipratik-sidequests
          directory: sidequests
          branch: master